sass:
    load_paths:
        - _sass
        - node_modules
    style: compressed

exclude:
  - vendor
  - deploy.sh
  - node_modules
  - Makefile
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - packages.json
